baseURL = "https://sondos.click/"
languageCode = "en-us"
title = "Sondos Click"
enableRobotsTXT = true

theme = "github.com/nunocoracao/blowfish/v2"

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"
