baseURL = "https://sondos.click/"
title = "Sondos Clicks"
enableRobotsTXT = true
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = false

[languages]
  [languages.es]
    languageCode = "es"
    languageName = "ES"
    weight = 1
  [languages.en]
    languageCode = "en"
    languageName = "EN"
    weight = 2

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"
