baseURL = "https://sondos.click/"
languageCode = "es-es"
title = "Sondos Clicks"
enableRobotsTXT = true
defaultContentLanguage = "es"
defaultContentLanguageInSubdir = false

[languages]
  [languages.es]
    languageName = "Espa√±ol"
    weight = 1
    title = "Sondos Clicks"
    languageCode = "es-es"

  [languages.en]
    languageName = "English"
    weight = 2
    title = "Sondos Clicks"
    languageCode = "en-us"

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"
