colorScheme = "github"
defaultAppearance = "light"
autoSwitchAppearance = false
enableSearch = true
mainSections = ["posts"]
logo = "images/brand/sondos-logo-symbol.svg"

[homepage]
  layout = "custom"
  showRecent = true
  showRecentItems = 5
  cardView = false
  cardViewScreenWidth = false

[article]
  showDate = true
  showReadingTime = true
  showTableOfContents = true

[list]
  showCards = true

[author]
  name = "sondosclicks"
  headline = "A dos clicks de PRO"
  bio = "Cuaderno simple de ideas, historias y pequeños experimentos… con la seriedad justa y una pizca de ironía."
  image = "images/brand/sondos-avatar.svg"

[[author.links]]
  github = "https://github.com/sondosclick"

[[author.links]]
  linkedin = "https://www.linkedin.com/in/roque-rivera"

[plausible]
  enable = true
  domain = "sondos.click"
  gitstar = false
