colorScheme = "github"
defaultAppearance = "light"
autoSwitchAppearance = false
enableSearch = true
mainSections = ["posts"]
logo = "images/brand/sondos-logo-symbol.svg"

[homepage]
  layout = "custom"
  showRecent = true
  showRecentItems = 5
  cardView = true
  cardViewScreenWidth = true

[article]
  showDate = true
  showReadingTime = true
  showTableOfContents = true

[author]
  name = "sondosclicks"
  headline = "A dos clicks de PRO"
  bio = "Cuaderno simple de ideas, historias y pequeños experimentos… con la seriedad justa y una pizca de ironía."
  image = "images/brand/sondos-avatar.svg"

[[author.links]]
  github = "https://github.com/sondosclick"

[[author.links]]
  linkedin = "https://www.linkedin.com/"
