title: "sondos.click"
email: ""
description: "A personal IT blog: A dos Clicks de Producción — sarcastic takes on cloud & AI."
baseurl: "/sondos.click" # set if serving from /repo-name
url: "https://sondosclick.github.io" # optional; GitHub Pages will set actual URL
slogan: "A dos Clicks de Producción"
author:
  name: "sondosclick"
theme: minima
paginate: 10
plugins: []
permalink: "/:categories/:title/"
